baseURL = "https://girishluckhun.com"
title   = "Girish Luckhun"
languageCode = "en-us"
theme = "hello-friend-ng"

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
disableRSS      = false
disableSitemap  = false
disable404      = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  name = "Girish Luckhun"

  [params.author]
    name = "Girish Luckhun"  # ✅ Correct structure expected by the theme


  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Girish Luckhun's Homepage"
  keywords = "Girish Luckhun, homepage, blog"
  images = [""]

  homeSubtitle = "Technophile | Linux Enthusiast | Introvert | and other nerd stuff"
  backgroundImage = "/images/bck.jpeg"
  gitUrl = "https://github.com/RitLuck"

  disableReadOtherPosts = false
  enableThemeToggle = true
  enableSharingButtons = true
  enableGlobalLanguageMenu = false
  justifyContent = true

  [params.footer]
    trademark = true
    author = true
    topText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "<a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">Theme</a>"
    ]

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = "$"
    logoText     = "cd /home/"
    logoHomeLink = "/"
    logoCursorColor = "#fffff"

  [params.portrait]
    path     = "/images/pic.jpeg"
    alt      = "Portrait"
    maxWidth = "256px"

  [[params.social]]
    name = "twitter"
    url  = "https://x.com/sudo_gluck"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/girish-luckhun-7a19bb184/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/RitLuck"

  [[params.social]]
    name = "email"
    url  = "mailto:r.luckhun@yahoo.com"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[menu]
  [[menu.main]]
    identifier = "whoami"
    name       = "whoami"
    url        = "/whoami/"
    weight     = 10

  [[menu.main]]
    identifier = "posts"
    name       = "~/posts"
    url        = "/posts/"
    weight     = 20

  [[menu.main]]
    identifier = "Techinical_posts"
    name       = "~/technical"
    url        = "technical/"
    weight     = 30

  [[menu.main]]
    identifier = "tags"
    name       = "~/tags"
    url        = "/tags/"
    weight     = 40

  [[menu.main]]
    identifier = "anime"
    name = "~/mylist"
    url = "/my_list/"
    weight = 1

